### ISSUE TITLE
this._timeout is null when disabling

### ISSUE THREAD

**Issue by diegopvlk** [pesader/gnome-shell-extension-foresight#7]
When disabling the extension this error shows: `TypeError: this._timeout is null`

It's a problem because the extension gets disabled when locking the screen or suspending.

**Comment by pesader** [comment]
@diegopvlk Thank you for the bug report!

I just committed a fix which seems to work for me. Could you please test it out and let me know if it's working for you too?

**Comment by forteller** [comment]
Hi. I still have this issue on version 5, I think. Is v5 the latest? According to EGO it is.

**Comment by pesader** [comment]
Hi, I hadn't submitted the latest codebase for review on EGO yet because I wanted to make some progress on #9 first. I have now submitted it for review, you can follow the progress here: https://extensions.gnome.org/review/62581

**Comment by forteller** [comment]
Thank you! The update came, and it works now!
